export const phonecodes = [
    {value: "al", label: "+355"},
    {value: "ad", label: "+376"},
    {value: "at", label: "+43"},
    {value: "by", label: "+375"},
    {value: "be", label: "+32"},
    {value: "ba", label: "+387"},
    {value: "bg", label: "+359"},
    {value: "hr", label: "+385"},
    {value: "cy", label: "+357"},
    {value: "cz", label: "+420"},
    {value: "dk", label: "+45"},
    {value: "ee", label: "+372"},
    {value: "fo", label: "+298"},
    {value: "fi", label: "+358"},
    {value: "fr", label: "+33"},
    {value: "de", label: "+49"},
    {value: "gi", label: "+350"},
    {value: "gr", label: "+30"},
    {value: "hu", label: "+36"},
    {value: "is", label: "+354"},
    {value: "ie", label: "+353"},
    {value: "it", label: "+39"},
    {value: "lv", label: "+371"},
    {value: "li", label: "+423"},
    {value: "lt", label: "+370"},
    {value: "lu", label: "+352"},
    {value: "mk", label: "+389"},
    {value: "mt", label: "+356"},
    {value: "md", label: "+373"},
    {value: "mc", label: "+377"},
    {value: "me", label: "+382"},
    {value: "nl", label: "+31"},
    {value: "no", label: "+47"},
    {value: "pl", label: "+48"},
    {value: "pt", label: "+351"},
    {value: "ro", label: "+40"},
    {value: "ru", label: "+7"},
    {value: "sm", label: "+378"},
    {value: "rs", label: "+381"},
    {value: "sk", label: "+421"},
    {value: "si", label: "+386"},
    {value: "es", label: "+34"},
    {value: "se", label: "+46"},
    {value: "ch", label: "+41"},
    {value: "tr", label: "+90"},
    {value: "ua", label: "+380"},
    {value: "gb", label: "+44"},
    {value: "va", label: "+379"},
];

export const countries = [

    {value: "Albania", label: "Albania"},
    {value: "Andorra", label: "Andorra"},
    {value: "Austria", label: "Austria"},
    {value: "Belarus", label: "Belarus"},
    {value: "Belgium", label: "Belgium"},
    {value: "Bosnia and Herzegovina", label: "Bosnia and Herzegovina"},
    {value: "Bulgaria", label: "Bulgaria"},
    {value: "Croatia", label: "Croatia"},
    {value: "Cyprus", label: "Cyprus"},
    {value: "Czech Republic", label: "Czech Republic"},
    {value: "Denmark", label: "Denmark"},
    {value: "Estonia", label: "Estonia"},
    {value: "Faroe Islands", label: "Faroe Islands"},
    {value: "Finland", label: "Finland"},
    {value: "France", label: "France"},
    {value: "Germany", label: "Germany"},
    {value: "Gibraltar", label: "Gibraltar"},
    {value: "Greece", label: "Greece"},
    {value: "Hungary", label: "Hungary"},
    {value: "Iceland", label: "Iceland"},
    {value: "Ireland", label: "Ireland"},
    {value: "Italy", label: "Italy"},
    {value: "Latvia", label: "Latvia"},
    {value: "Liechtenstein", label: "Liechtenstein"},
    {value: "Lithuania", label: "Lithuania"},
    {value: "Luxembourg", label: "Luxembourg"},
    {value: "North Macedonia", label: "North Macedonia"},
    {value: "Malta", label: "Malta"},
    {value: "Moldova", label: "Moldova"},
    {value: "Monaco", label: "Monaco"},
    {value: "Montenegro", label: "Montenegro"},
    {value: "Netherlands", label: "Netherlands"},
    {value: "Norway", label: "Norway"},
    {value: "Poland", label: "Poland"},
    {value: "Portugal", label: "Portugal"},
    {value: "Romania", label: "Romania"},
    {value: "Russian Federation", label: "Russian Federation"},
    {value: "San Marino", label: "San Marino"},
    {value: "Serbia", label: "Serbia"},
    {value: "Slovakia", label: "Slovakia"},
    {value: "Slovenia", label: "Slovenia"},
    {value: "Spain", label: "Spain"},
    {value: "Sweden", label: "Sweden"},
    {value: "Switzerland", label: "Switzerland"},
    {value: "Turkey", label: "Turkey"},
    {value: "Ukraine", label: "Ukraine"},
    {value: "United Kingdom", label: "United Kingdom"},
    {value: "Vatican City", label: "Vatican City"}
]

