export const phonecodes = [
    {value: "al", label: "+355"},
    {value: "ad", label: "+376"},
    {value: "at", label: "+43"},
    {value: "by", label: "+375"},
    {value: "be", label: "+32"},
    {value: "ba", label: "+387"},
    {value: "bg", label: "+359"},
    {value: "hr", label: "+385"},
    {value: "cy", label: "+357"},
    {value: "cz", label: "+420"},
    {value: "dk", label: "+45"},
    {value: "ee", label: "+372"},
    {value: "fo", label: "+298"},
    {value: "fi", label: "+358"},
    {value: "fr", label: "+33"},
    {value: "de", label: "+49"},
    {value: "gi", label: "+350"},
    {value: "gr", label: "+30"},
    {value: "hu", label: "+36"},
    {value: "is", label: "+354"},
    {value: "ie", label: "+353"},
    {value: "it", label: "+39"},
    {value: "lv", label: "+371"},
    {value: "li", label: "+423"},
    {value: "lt", label: "+370"},
    {value: "lu", label: "+352"},
    {value: "mk", label: "+389"},
    {value: "mt", label: "+356"},
    {value: "md", label: "+373"},
    {value: "mc", label: "+377"},
    {value: "me", label: "+382"},
    {value: "nl", label: "+31"},
    {value: "no", label: "+47"},
    {value: "pl", label: "+48"},
    {value: "pt", label: "+351"},
    {value: "ro", label: "+40"},
    {value: "ru", label: "+7"},
    {value: "sm", label: "+378"},
    {value: "rs", label: "+381"},
    {value: "sk", label: "+421"},
    {value: "si", label: "+386"},
    {value: "es", label: "+34"},
    {value: "se", label: "+46"},
    {value: "ch", label: "+41"},
    {value: "tr", label: "+90"},
    {value: "ua", label: "+380"},
    {value: "gb", label: "+44"},
    {value: "va", label: "+379"},
];

export const countries = [
    {value: "Albania", label: "Albania", code: "AL"},
    {value: "Andorra", label: "Andorra", code: "AD"},
    {value: "Austria", label: "Austria", code: "AT"},
    {value: "Belarus", label: "Belarus", code: "BY"},
    {value: "Belgium", label: "Belgium", code: "BE"},
    {value: "Bosnia and Herzegovina", label: "Bosnia and Herzegovina", code: "BA"},
    {value: "Bulgaria", label: "Bulgaria", code: "BG"},
    {value: "Croatia", label: "Croatia", code: "HR"},
    {value: "Cyprus", label: "Cyprus", code: "CY"},
    {value: "Czech Republic", label: "Czech Republic", code: "CZ"},
    {value: "Denmark", label: "Denmark", code: "DK"},
    {value: "Estonia", label: "Estonia", code: "EE"},
    {value: "Faroe Islands", label: "Faroe Islands", code: "FO"},
    {value: "Finland", label: "Finland", code: "FI"},
    {value: "France", label: "France", code: "FR"},
    {value: "Germany", label: "Germany", code: "DE"},
    {value: "Gibraltar", label: "Gibraltar", code: "GI"},
    {value: "Greece", label: "Greece", code: "GR"},
    {value: "Hungary", label: "Hungary", code: "HU"},
    {value: "Iceland", label: "Iceland", code: "IS"},
    {value: "Ireland", label: "Ireland", code: "IE"},
    {value: "Italy", label: "Italy", code: "IT"},
    {value: "Latvia", label: "Latvia", code: "LV"},
    {value: "Liechtenstein", label: "Liechtenstein", code: "LI"},
    {value: "Lithuania", label: "Lithuania", code: "LT"},
    {value: "Luxembourg", label: "Luxembourg", code: "LU"},
    {value: "North Macedonia", label: "North Macedonia", code: "MK"},
    {value: "Malta", label: "Malta", code: "MT"},
    {value: "Moldova", label: "Moldova", code: "MD"},
    {value: "Monaco", label: "Monaco", code: "MC"},
    {value: "Montenegro", label: "Montenegro", code: "ME"},
    {value: "Netherlands", label: "Netherlands", code: "NL"},
    {value: "Norway", label: "Norway", code: "NO"},
    {value: "Poland", label: "Poland", code: "PL"},
    {value: "Portugal", label: "Portugal", code: "PT"},
    {value: "Romania", label: "Romania", code: "RO"},
    {value: "Russian Federation", label: "Russian Federation", code: "RU"},
    {value: "San Marino", label: "San Marino", code: "SM"},
    {value: "Serbia", label: "Serbia", code: "RS"},
    {value: "Slovakia", label: "Slovakia", code: "SK"},
    {value: "Slovenia", label: "Slovenia", code: "SI"},
    {value: "Spain", label: "Spain", code: "ES"},
    {value: "Sweden", label: "Sweden", code: "SE"},
    {value: "Switzerland", label: "Switzerland", code: "CH"},
    {value: "Turkey", label: "Turkey", code: "TR"},
    {value: "Ukraine", label: "Ukraine", code: "UA"},
    {value: "United Kingdom", label: "United Kingdom", code: "GB"},
    {value: "Vatican City", label: "Vatican City", code: "VA"}
]

export const currencyOptions = [
    {value:"BGN",label:"BGN",image:"BG"},
    {value:"EUR",label:"EUR",image:"EU"},
    {value:"RUB",label:"RUB",image:"RU"},
    {value:"USD",label:"USD",image:"US"},
    {value:"GBP",label:"GBP",image:"GB"},
    {value:"RON",label:"RON",image:"RO"},
    {value:"TRY",label:"TRY",image:"TR"},
]
